---
title: "Readme"
author: "Dorianeve"
date: "19/3/2019"
output: html_document:
        keep_md: yes
---

Peer-graded Assignment: Getting and Cleaning Data Course Project
This repository is a Dorianeve submission for Getting and Cleaning Data course project. 
It has the instructions on how to run analysis on the tidydataset.

Files
CodeBook.md a code book that describes the variables and the data.

run_analysis.R descrives the data preparation and then followed by the 5 steps:

Merges the training and the test sets to create one data set.
Extracts only the measurements on the mean and standard deviation for each measurement.
Uses descriptive activity names to name the activities in the data set
Appropriately labels the data set with descriptive variable names.
From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
tidydataset.txt is the exported final data after going through all the sequences described above.

